# Site settings
title: 'Adrian Sosa'
description: "Adrian's personal web site"
url: 'https://adriansosauv.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Adrian Sosa'
  email: contact@adriansosa.net
  twitter_username: AdrinSo24822337
  facebook_username: AdriannSM
  github_username:  AdrianSosaUV
  linkedin_username:  adrian-sosa-medellin

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
